### ISSUE TITLE
Fatal error: Class 'DataFunctions' not found in ../administration/updatesettings.php

### ISSUE THREAD

**Issue by xstresedg** [phpcollab/phpcollab#38] opened 2019-05-06 17:58 UTC
# Issue Report

Remove the above from the issue description and make sure the following checklist is followed:

- [] phpCollab version used: 2.6.4
- [] PHP version (e.g. 5.3, 7.x): 5.6.40
- [] Web server and version (Apache, nginx): Apache/2.4.39 (cPanel) OpenSSL/1.0.2r mod_bwlimited/1.4 
- [] Steps to duplicate the problem: Fresh install via Softilicious, modifying any existing item (task, project, client, phpCollab settings) cause this error to be triggered in the error_log file. Website is presented as "This page isn’t working <domain> is currently unable to handle this request. HTTP ERROR 500"
- [] Stacktraces and phpCollab/PHP DEBUG logs where appropriate.
[error_log.zip](https://github.com/phpcollab/phpcollab/files/3149227/error_log.zip)

NOTE: I will offer whatever services I can. I was able to make the updatesettings.php work by commenting out:
"$dataFunction = new DataFunctions();
   $scrubedData = $dataFunction->scrubData($_POST);
   extract($scrubedData);"
but that only fixes the one page, and I imagine the DataFunctions is being used as some sort of verification check of information. I'd have to comment out all of the files, and I do not know which files have and which do not. I apologize if this was a silly issue to post.

Let me know how I can help!

**Comment by mindblender** [comment] 2019-05-17 03:07
@cmkos Thanks for bringing this to our attention.  I will take a look and see what the issue is.

**Comment by mindblender** [comment] 2019-05-18 07:14
It appears that the dataScrub method is only used in the update code.  I have added this to the list of things to look into.

**Comment by mindblender** [comment] 2020-01-22 22:12
This appears to be fixed in v.2.7.x.  Closing this issue.  Please reopen if you are still having this problem.

**Closed by mindblender** 2020-01-22 22:12 UTC
