### ISSUE TITLE
Reassign task error

### ISSUE THREAD

**Issue by theedo** [phpcollab/phpcollab#75] opened 2022-01-01 00:13 UTC
Debian 11 Bullseye
- [] phpCollab version: 2.10.3
- [] PHP version: 7.4.25
- [] Web server: Apache2 version 2.4.51-1

- [] Steps to duplicate the problem
Try to edit and existng task and assign it to a different use than originally assigned to.
click submit. Leads to error message Ooof! phpcollab appears to have fallen down.

- [] Stacktraces and phpCollab/PHP DEBUG logs where appropriate.
FATAL ERROR (2): TypeError: Argument 1 passed to phpCollab\Tasks\Tasks::updateTask() must be of the type int, string given, called in /var/www/html/programs/phpcollab/tasks/edittask.php on line 385 and defined in /var/www/html/programs/phpcollab/classes/Tasks/Tasks.php:510
Stack trace:
#0 /var/www/html/programs/phpcollab/tasks/edittask.php(385): phpCollab\Tasks\Tasks->updateTask()
#1 {main}

**Comment by mindblender** [comment] 2022-01-03 03:01
I confirmed this issue and have fixed it. The fix will be in the next release.

**Comment by ISharlsI** [comment] 2022-01-25 07:48
@theedo hi, how did you managed to install phpcollab in debian 11? I know this sounds weird but I'm new in linux. In the setup window I keep getting the same error message when I try to save the settings. The error says "We had a problem completing the request. Please check  and try again" I do not know if it is because I can't do the chown apache, it says that the user does not exist, or I do not know if it is something with my database. I would apreciate an answer

**Comment by mindblender** [comment] 2022-01-25 16:57
@ISharlsI  Is this related to the notifications issue?  If this is not related to the original notification issue, please create a new issue with the proper details.

As for troubleshooting, if you check the PHP error log, there might be more information about what failed that could help resolve the issue.

**Closed** 2022-06-04 05:39 UTC
Labels: bug
