### ISSUE TITLE
Bulletin Board - Added text is not visible

### ISSUE THREAD

**Issue by packetflow** [phpcollab/phpcollab#23] opened 2016-10-14 15:44 UTC
Hi,

found an issue that if we open a discussion the text "Message :" is always not visible/empty. Issue does not depend on if project manager adds it or customer.

Details:
Version 2.5.1
Server version: Apache/2.4.20 (FreeBSD)
PHP 5.6.21
mysql  5.7.10

Do we need any additional information?

Cheers,
*p

**Comment by mindblender** [comment] 2016-10-14 16:14
Thanks for reporting this.  We will take a look at it.

**Comment by mindblender** [comment] 2017-07-26 03:29
@packetflow 

The master branch has been updated with a lot of changes in the code structure/logic. It should still be compatible with your existing database if you want to give it a try and see if it fixes your issue. Please note that the master branch is NOT an official release so you are highly recommended to backup your installation first.

Closing this, please re-open if you test and the issue is still there.

**Closed by mindblender** 2017-07-26 03:29 UTC
